sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WY2ATBErfk/6C8h1Him+NNepm/lQGdAmlVSVghHur//+5sBgpYGXE74idnRPf6BJl2lqjFn32u2iQUP8YPfLmR8gQPtUShUnk9+U2O6icMdFprZ909VK2BBWSA81kIlBiqIDHNr4nApSOAfoPfrnJJelmsdBTymEox+QuK0A90YDrs7D5SW0FzWQ2Mj0u69yrzNRyMkj5xtz95vqcKx1OfbzdIq4O1xJkRPBvhwZGZV+QNsOBahuG18I2CrDeHC/L1a+wsgTDcki5KhWY6vB4eqCiSb9cMVa+kXglKbvalKmx54HWkICcCgwscE00y+0yzzl7J6/qlBkiPOmGYCULAhxUfcNgtKa2pkO52kAL6OuU0X+/X4ZFnvE1NszWxT+lYLTUy8TtGk51c62qPacSW2rAauVLJQjWyppjVP26MBfbts1pBLgayd/PXNKQ+kK8B9rCx2K7TdkuKXNTTGEJlLAXpM6EtOqXzhatsDxpzoUy0/fGvq6ZcaThUBSjJwyJUDBdwPINjQi9408gT4JnRDpDUtk3IMnz4wJZoxbXzSc7T5bvq8OHz5/j43I/Mqtg6/HRnAeR/yCtHSpVtjPhEyhZNYGDcADsWUzGtxzB+WGJqNPYxho7eaz1X5GpvuusGkYxgy+xUIvuH68j5naR35FvtTIielDq4Gicf0kRw0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Rebecca-of-Sunnybrook-Farm_498
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy